### ISSUE TITLE
`st_write()` skips the first column when `append=T`

### ISSUE THREAD

**Issue by Rtt398** [r-spatial/sf#2256]
I want to export sf objects to a csv file with `st_write()` function. There is a lot of data, so I want to write it sequentially.
The first write works as expected, but when I try to append the second and subsequent times, the first column of the sf object is ignored.
Am I doing something wrong? Please help me.

Thank you,

----

**To Reproduce**
```
library(sf)
# Linking to GEOS 3.10.2, GDAL 3.4.1, PROJ 7.2.1; sf_use_s2() is TRUE
nc = st_read(system.file("gpkg/nc.gpkg", package="sf"))
st_write(nc, "D:/xxxxx/nc.csv", layer_options = "GEOMETRY=AS_WKT")
st_write(nc, "D:/xxxxx/nc.csv", layer_options = "GEOMETRY=AS_WKT", append = T)
```

Even though the same data is written twice, the second time the first column, "AREA" is not written.

<details>

R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

other attached packages:
[1] sf_1.0-14

GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H           PROJ 
"3.10.2"        "3.4.1"        "7.2.1"         "true"         "true"        "7.2.1" 
</details>

**Comment by edzer** [comment]
With
```r
Linking to GEOS 3.11.1, GDAL 3.6.4, PROJ 9.1.1; sf_use_s2() is TRUE
```
I cannot confirm, so this may have been an upstream (GDAL) issue that is now solved. I believe that if you update R to the 4.3.2 version and reinstall `sf` you get it with a newer GDAL version.

**Comment by Rtt398** [comment]
I tried updating R and reinstalling `sf`, but it didn't solve the problem.
```
> library(sf)
Linking to GEOS 3.11.2, GDAL 3.7.2, PROJ 9.3.0; sf_use_s2() is TRUE
> nc = st_read(system.file("gpkg/nc.gpkg", package="sf"))
Reading layer `nc.gpkg' from data source `C:\Users\xxx\AppData\Local\R\win-library\4.3\sf\gpkg\nc.gpkg' using driver `GPKG'
Simple feature collection with 100 features and 14 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
Geodetic CRS:  NAD27
> st_write(nc, "E:/xxxxx/nc.csv", layer_options = "GEOMETRY=AS_WKT")
Writing layer `nc' to data source `E:/xxxxx/nc.csv' using driver `CSV'
options:        GEOMETRY=AS_WKT 
Writing 100 features with 14 fields and geometry type Multi Polygon.
> st_write(nc, "E:/xxxxx/nc.csv", layer_options = "GEOMETRY=AS_WKT", append = T)
Updating layer `nc' to data source `E:/xxxxx/nc.csv' using driver `CSV'
options:        GEOMETRY=AS_WKT 
Updating existing layer nc
Writing 100 features with 14 fields and geometry type Multi Polygon.
```
The result is the same. I attach the csv file.
[nc.csv](https://github.com/r-spatial/sf/files/13284721/nc.csv)

**Comment by edzer** [comment]
Weird!

**Comment by edzer** [comment]
> what does this meaning: sf_use_s2()?

It means that when working with geodetic (unprojected) coordinates, for geometrical operations `sf` will use as far as possible the s2geometry library, rather than GEOS which is meant for planar (projected) coordinates.

**Comment by edzer** [comment]
`sf` doesn't do anything particular here, so if you want to push this try to reproduce it with gdal tools (ogr2ogr and such) and report it upstream (OSGeo/gdal repo).
